name: CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write
    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Create myfirstproject.json with GDrive credentials
      - name: Create GDrive credentials
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          echo $GDRIVE_CREDENTIALS_DATA > myfirstproject.json

      # Add the DVC remote
      - name: Add DVC Remote
        run: |
          uv run dvc remote add -d gdrive-remote gdrive://1rAlcFkM9POmRdF_TZ74K8G_8tsFFtD2g

      # Modify the DVC remote with credentials
      - name: Modify DVC Remote
        run: |
          uv run dvc remote modify --local gdrive-remote gdrive_service_account_json_file_path myfirstproject.json

      # Pull data from DVC
      - name: DVC Pull Data
        run: |
          uv run dvc pull

      # Run CNN Inference
      - name: Run tests
        run: |
          mkdir -p ./plots
          python3 main.py --mode test --data_path ./data/test/ --model_path ./models/cnn_resnet18_freeze_backbone_False.pth

