name: CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install uv CLI
      - name: Install uv CLI
        uses: astral-sh/setup-uv@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install uv  # Ensure uv is installed
          pip install dvc[gdrive]

      # DVC configuration
      - name: Create myfirstproject.json
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          echo $GDRIVE_CREDENTIALS_DATA > myfirstproject.json

      - name: Add and configure DVC remote
        run: |
          uv run dvc remote add -d gdrive-remote gdrive://1rAlcFkM9POmRdF_TZ74K8G_8tsFFtD2g
          uv run dvc remote modify --local gdrive-remote gdrive_service_account_json_file_path myfirstproject.json

      - name: Pull DVC data
        run: |
          uv run dvc pull -v

      # Run CNN Inference
      - name: Run tests
        run: |
          mkdir -p /home/runner/work/projectML/projectML/plots
          python3 main.py --mode test --data_path ./data/test/ --model_path ./models/cnn_resnet18_freeze_backbone_False.pth

      # Train CNN Model with MLflow
      - name: Train CNN with MLflow
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        run: |
          echo "MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}"
          mkdir -p /home/runner/work/projectML/projectML/plots
          python3 train.py --data_path ./data/train/ --epochs 50 --learning_rate 0.001 --model_dir ./models --plot_dir ./plots
